GET http://localhost:3003/api/notes/
###
GET http://localhost:3003/api/notes/673e3c1c93212c0807d2a354
###
POST http://localhost:3003/api/notes/
Content-Type: application/json

{
    "content": "Browser can execute only JavaScript",
    "important": "false"
}
###
PUT http://localhost:3003/api/notes/673f2343bdd5f5c539b34df5
Content-Type: application/json

{
    "content": "Sixth part",
    "important": "false"
}
###
DELETE http://localhost:3003/api/notes/67416d18e40f2ae6f7eb29be
###
POST http://localhost:3003/api/notes/
Content-Type: application/json

{
    "content": "Note created with user id",
    "important": "true",
    "userId": "675f050e3f2af3ecac056aca"
}
###
POST http://localhost:3003/api/notes/
Content-Type: application/json

{
    "content": "Note created by Galadriel",
    "important": "true",
    "userId": "675effc6306f2e0431bed875"
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username":"johndoe",
    "name": "john",
    "password": "sdfudsfs7das"

}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username":"root",
    "password": "sdfudsfaas7das"

}


