GET  http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"String",
    "author":"String",
    "url":"String",
    "likes": 61
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"One",
    "author":"John Doe",
    "url":"blog.somthing/one/",
    "likes":77 
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbmRhbGYiLCJpZCI6IjY3Njg1ZGIxN2VkZmQ4NjdhYzFkMjlmOSIsImlhdCI6MTczNDk1ODI3NSwiZXhwIjoxNzM0OTYxODc1fQ.qQdV6sAbE6Jei1EC-p5jjR5-ATXHHdBjtih_eAsLr90 
{
    "title":"Blog3",
    "author":"gandald",
    "url":"aragorn.gond/forest/",
    "userId":"67685db17edfd867ac1d29f9"
}

###
PUT http://localhost:3003/api/blogs/67580e36380c0d20c88fbe5a
Content-Type: application/json

{
    "title":"Updated",
    "author":"John Doe",
    "url":"blog.somthing/one/"
}
###
DELETE http://localhost:3003/api/blogs/67695aab0e631879db826294
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbmRhbGYiLCJpZCI6IjY3Njg1ZGIxN2VkZmQ4NjdhYzFkMjlmOSIsImlhdCI6MTczNDk1ODUwOCwiZXhwIjoxNzM0OTYyMTA4fQ.DuXNi60vnnMejyOhy6ja5jS7ldMCaSaUBCNRYoXxADI
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "gandalf",
    "name": "Gandalf",
    "password": "hello"
}

###
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username":"gandalf",
    "password": "hello"

}
###