GET  http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"String",
    "author":"String",
    "url":"String",
    "likes": 61
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"One",
    "author":"John Doe",
    "url":"blog.somthing/one/",
    "likes":77 
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"One no likes",
    "author":"John Doe",
    "url":"blog.somthing/one/"
}

###
PUT http://localhost:3003/api/blogs/67580e36380c0d20c88fbe5a
Content-Type: application/json

{
    "title":"Updated",
    "author":"John Doe",
    "url":"blog.somthing/one/"
}
###
DELETE http://localhost:3003/api/blogs/675025336e144e8fa4eb0578