GET http://localhost:3001/api/notes/
###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Javascript lives in the browser",
    "important": "true"
}
###
DELETE http://localhost:3001/api/notes/674165258bc906135e7a8f81


