GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/67404cfc4812c1229089215c

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{       
  "name": "Adams", 
  "number": "39-44-5323523"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{       
  "name": "DG", 
  "number": "39-44-5323523"
}
###
PUT http://localhost:3001/api/persons/67404cfc4812c1229089215c
Content-Type: application/json

{       
  "name": "John must Code", 
  "number": "39-44-1111"
}
###
DELETE http://localhost:3001/api/persons/2